// vue/players_CRUD/src/App.vue
<!-- 
  COPY AND PASTE YOUR CODE FROM THE PREVIOUS EXERCISE HERE. Also implement the following:

  1. Create a method for adding a new player. This method should handle the logic for adding a new player to the database and updating the players array. This method should also reset the form only if the request was successful. This method should be called when the add player form is submitted.

  2. Create a method for deleting a player. This method should handle the logic for deleting a player from the database and updating the players array. This method should be called when the delete button is clicked in the SelectedPlayer component.

  3. Create a method for updating a player. This method should handle the logic for updating a player in the database and updating the players array. This method should be called when the update button is clicked in the SelectedPlayer component.
 -->

 <template>
  <div>
    <!-- Display the RequestStatus component with a title -->
    <div>
      <h2>Request Status</h2>
      <RequestStatus>
        <template v-slot:status>
          <div>{{ requestStatus }}</div>
        </template>
      </RequestStatus>
    </div>

    <!-- Display the AddPlayer component with a title and appropriate method -->
    <div>
      <h2>Add Player</h2>
      <AddPlayer @add-player="addPlayer"></AddPlayer>
    </div>

    <!-- Display the ListPlayers component with a title and appropriate props -->
    <div>
      <h2>List of Players</h2>
      <ListPlayers :getPlayer="getPlayer" :players="players"></ListPlayers>
    </div>

    <!-- Display the SelectedPlayer component with a title and appropriate prop -->
    <div>
      <h2>Selected Player</h2>
      <SelectedPlayer
        :player="selectedPlayer"
        @delete-player="deletePlayer"
        @put-player="updatePlayer"
      ></SelectedPlayer>
    </div>

  </div>
</template>

<script>
import RequestStatus from './components/RequestStatus.vue';
import ListPlayers from './components/ListPlayers.vue';
import SelectedPlayer from './components/SelectedPlayer.vue';
import AddPlayer from './components/AddPlayer.vue';

const REQ_STATUS = {
  loading: "Loading...",
  success: "Finished!",
  error: "An error has occurred!!!",
};

export default {
  components: {
    RequestStatus,
    ListPlayers,
    SelectedPlayer,
    AddPlayer,
  },
  data() {
    return {
      players: [],
      selectedPlayer: null,
      requestStatus: REQ_STATUS.loading,
    };
  },
  created() {
    // Fetch players data and display it upon component creation
    this.fetchAllPlayers();
  },
  methods: {
    // Method to fetch all players
    async fetchAllPlayers() {
      try {
        // Set loading status
        this.requestStatus = REQ_STATUS.loading;

        // Make API call to fetch all players
        const response = await fetch('http://localhost:3001/api/players');
        const data = await response.json();

        // Update players array with fetched data
        this.players = data;

        // Set success status
        this.requestStatus = REQ_STATUS.success;
      } catch (error) {
        // Set error status
        this.requestStatus = REQ_STATUS.error;
        console.error('Error fetching players:', error);
      }
    },

    // Method to fetch a specific player
    async getPlayer(playerId) {
      try {
        // Set loading status
        this.requestStatus = REQ_STATUS.loading;

        // Make API call to fetch a specific player
        const response = await fetch(`http://localhost:3001/api/players/${playerId}`);
        const data = await response.json();

        // Update selectedPlayer with fetched data
        this.selectedPlayer = data;

        // Set success status
        this.requestStatus = REQ_STATUS.success;
      } catch (error) {
        // Set error status
        this.requestStatus = REQ_STATUS.error;
        console.error('Error fetching player:', error);
      }
    },

    // Method to add a new player
    async addPlayer(newPlayerName) {
      try {
        // Set loading status
        this.requestStatus = REQ_STATUS.loading;

        // Make API call to add a new player
        const response = await fetch('http://localhost:3001/api/players', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({ name: newPlayerName }),
        });

        const data = await response.json();

        // Update players array with the new player
        this.players.push(data);

        // Set success status
        this.requestStatus = REQ_STATUS.success;
      } catch (error) {
        // Set error status
        this.requestStatus = REQ_STATUS.error;
        console.error('Error adding player:', error);
      }
    },

    // Method to delete a player
    async deletePlayer(playerId) {
      try {
        // Set loading status
        this.requestStatus = REQ_STATUS.loading;

        // Make API call to delete a player
        await fetch(`http://localhost:3001/api/players/${playerId}`, {
          method: 'DELETE',
        });

        // Update players array by removing the deleted player
        this.players = this.players.filter((player) => player.id !== playerId);

        // Set success status
        this.requestStatus = REQ_STATUS.success;
      } catch (error) {
        // Set error status
        this.requestStatus = REQ_STATUS.error;
        console.error('Error deleting player:', error);
      }
    },

    // Method to update a player
    async updatePlayer(newPlayerState) {
      try {
        // Set loading status
        this.requestStatus = REQ_STATUS.loading;

        // Make API call to update a player
        const response = await fetch(`http://localhost:3001/api/players/${this.selectedPlayer.id}`, {
          method: 'PUT',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({ isActive: newPlayerState }),
        });

        const updatedPlayer = await response.json();

        // Update players array with the updated player
        this.players = this.players.map((player) =>
          player.id === updatedPlayer.id ? updatedPlayer : player
        );

        // Set success status
        this.requestStatus = REQ_STATUS.success;
      } catch (error) {
        // Set error status
        this.requestStatus = REQ_STATUS.error;
        console.error('Error updating player:', error);
      }
    },
  },
};
</script>

// react/players_CRUD2/src/App.jsx
/** @format
 * Copy paste your code from the App.jsx file here from the previous exercise.
 *
 * Use similar logic as in the Vue CRUD2 exercise and add authentication to the app.
 * 
 * Backend is still using Basic Auth, so you must use the same logic as in the Vue exercise. 
 * 
 * REMEMBER: use the same ids, classes and attributes as in the Vue exercise in the same places to pass the tests. Remember to pass in the appropriate props to the child components. 

 * BEWARE: The component props may be different from the Vue exercise and the tests will not pass if you use the wrong props.
 */

import { useState, useEffect } from "react";
import { REQ_STATUS } from "../cypress/e2e/constants.js";
import { ListPlayers } from "./components/ListPlayers.jsx";
import { SelectedPlayer } from "./components/SelectedPlayer.jsx";
import { RequestStatus } from "./components/RequestStatus.jsx";
import { AddPlayer } from "./components/AddPlayer.jsx";
import { AuthUser } from "./components/AuthUser.jsx";

const url = "http://localhost:3001/api/players";

function App() {
  const [players, setPlayers] = useState([]);
  const [selectedPlayer, setSelectedPlayer] = useState(null);
  const [requestStatus, setRequestStatus] = useState(REQ_STATUS.loading);
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const [userCredentials, setUserCredentials] = useState(null);

  useEffect(() => {
    if (isLoggedIn) {
      fetchAllPlayers();
    }
  }, [isLoggedIn]);

  const fetchAllPlayers = async () => {
    try {
      setRequestStatus(REQ_STATUS.loading);
      const response = await fetch(url, {
        headers: {
          Authorization: `Basic ${btoa(`${userCredentials.username}:${userCredentials.password}`)}`,
        },
      });
      const data = await response.json();
      console.log(data)
      setPlayers(data);
      setRequestStatus(REQ_STATUS.success);
    } catch (error) {
      console.error("Error fetching players:", error);
      setRequestStatus(REQ_STATUS.error);
    }
  };

  const getPlayer = async (playerId) => {
    try {
      setRequestStatus(REQ_STATUS.loading);
      const response = await fetch(`${url}/${playerId}`, {
        headers: {
          Authorization: `Basic ${btoa(`${userCredentials.username}:${userCredentials.password}`)}`,
        },
      });
      const data = await response.json();
      setSelectedPlayer(data);
      setRequestStatus(REQ_STATUS.success);
    } catch (error) {
      console.error("Error fetching player:", error);
      setRequestStatus(REQ_STATUS.error);
    }
  };

  const addPlayer = async (newPlayerName, e) => {
    e.preventDefault();
    try {
      setRequestStatus(REQ_STATUS.loading);
      const response = await fetch(url, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Basic ${btoa(`${userCredentials.username}:${userCredentials.password}`)}`,
        },
        body: JSON.stringify({ name: newPlayerName }),
      });
      const data = await response.json();
      setPlayers([...players, data]);
      setRequestStatus(REQ_STATUS.success);
    } catch (error) {
      console.error("Error adding player:", error);
      setRequestStatus(REQ_STATUS.error);
    }
  };

  const deletePlayer = async (playerId, e) => {
    e.preventDefault();
    try {
      setRequestStatus(REQ_STATUS.loading);
      const response = await fetch(`${url}/${playerId}`, {
        method: "DELETE",
        headers: {
          Authorization: `Basic ${btoa(`${userCredentials.username}:${userCredentials.password}`)}`,
        },
      });
      if (response.ok) {
        setPlayers(players.filter((player) => player.id !== playerId));
        setSelectedPlayer(null);
        setRequestStatus(REQ_STATUS.success);
      } else {
        setRequestStatus(REQ_STATUS.error);
      }
    } catch (error) {
      console.error("Error deleting player:", error);
      setRequestStatus(REQ_STATUS.error);
    }
  };

  const updatePlayer = async (e, playerId, newPlayerState) => {
    e.preventDefault();
    try {
      setRequestStatus(REQ_STATUS.loading);
      const response = await fetch(`${url}/${playerId}`, {
        method: "PUT",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Basic ${btoa(`${userCredentials.username}:${userCredentials.password}`)}`,
        },
        body: JSON.stringify({ isActive: newPlayerState }),
      });
      const updatedPlayer = await response.json();
      setPlayers(
        players.map((player) =>
          player.id === updatedPlayer.id ? updatedPlayer : player
        )
      );
      setRequestStatus(REQ_STATUS.success);
    } catch (error) {
      console.error("Error updating player:", error);
      setRequestStatus(REQ_STATUS.error);
    }
  };

  const registerUser = async (username, password) => {
    try {
      setRequestStatus(REQ_STATUS.loading);
      const response = await fetch("http://localhost:3001/api/users", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ username, password }),
      });
      if (response.ok) {
        setUserCredentials({ username, password });
        setIsLoggedIn(true);
        setRequestStatus(REQ_STATUS.success);
      } else {
        setRequestStatus(REQ_STATUS.error);
      }
    } catch (error) {
      console.error("Error registering user:", error);
      setRequestStatus(REQ_STATUS.error);
    }
  };

  const loginUser = async (username, password) => {
    try {
      setRequestStatus(REQ_STATUS.loading);
      const response = await fetch(url, {
        headers: {
          Authorization: `Basic ${btoa(`${username}:${password}`)}`,
        },
      });
      if (response.ok) {
        setUserCredentials({ username, password });
        setIsLoggedIn(true);
        setRequestStatus(REQ_STATUS.success);
      } else {
        setRequestStatus(REQ_STATUS.error);
      }
    } catch (error) {
      console.error("Error logging in:", error);
      setRequestStatus(REQ_STATUS.error);
    }
  };

  const logoutUser = () => {
    setIsLoggedIn(false);
    setUserCredentials(null);
    setPlayers([]);
    setSelectedPlayer(null);
    setRequestStatus(REQ_STATUS.success);
  };

  return (
    <div>
      <div>
        <h2>Authentication</h2>
        <AuthUser
          isLoggedIn={isLoggedIn}
          onLogin={loginUser}
          onRegister={registerUser}
          onLogout={logoutUser}
        />
      </div>

      <div>
        <h2>Request Status</h2>
        <RequestStatus>{requestStatus}</RequestStatus>
      </div>

      {isLoggedIn && (
        <div>
          <h2>Add Player</h2>
          <AddPlayer handleSubmit={addPlayer} />
        </div>
      )}

      {isLoggedIn && (
        <div>
          <h2>List of Players</h2>
          <ListPlayers players={players} getPlayer={getPlayer} />
        </div>
      )}

      {isLoggedIn && (
        <div>
          <h2>Selected Player</h2>
          <SelectedPlayer
            player={selectedPlayer}
            handleUpdate={updatePlayer}
            handleDelete={deletePlayer}
          />
        </div>
      )}
    </div>
  );
}

export default App;
