// react/players_fetch/src/components/ListPlayers.jsx
/** @format */

/** @format
 *
 * Student instructions:
 *
 * This component is used to display a list of players. It receives getPlayer and players as props.
 *
 * Create the component that you did in Vue now with React. Use provided props to handle user events. Find and replace functionality with React equivalents.
 *
 * NOTE: use the same ids, classes and html elements as you did in Vue. Refer to tests in the __tests__ folder to pass the unit tests, and to the cypress/e2e folder for the end-to-end tests.
 *
 * BEWARE: some tests do not pass if you do not handle the case where the players prop is an empty array, or null.
 *
 */

import { ListPlayer } from "./ListPlayer.jsx";

export const ListPlayers = ({ players, getPlayer }) => {
  const handlePlayerClicked = (playerId) => {
    getPlayer(playerId);
  };

  return (
    <div>
      <ul id="players-list">
        {players && players.length > 0 ? (
          players.map((player) => (
            <ListPlayer
              key={player.id}
              player={player}
              onClick={handlePlayerClicked}
            />
          ))
        ) : (
          <li>No players available</li>
        )}
      </ul>
    </div>
  );
};

// vue/players_fetch/src/components/ListPlayers.vue
<!-- 

  Useful to read: 
  - https://vuejs.org/guide/scaling-up/sfc.html
  - https://vuejs.org/guide/essentials/component-basics.html
  - https://vuejs.org/guide/essentials/list
  - https://vuejs.org/guide/components/props.html
  - https://vuejs.org/guide/components/events.html
  
  
  Student instructions: 

  This component is used to display a list of players. It receives getPlayer and players as props.

  1. Create an unordered list with an id of players-list. Render the ListPlayer component for each player in the list.

  2. Listen for "player-clicked" events from the ListPlayer component, and call the getPlayer prop function with the id of the clicked player as an argument.

-->
<template>
  <div>
    <ul id="players-list">
      <ListPlayer
        v-for="player in players"
        :key="player.id"
        :player="player"
        @player-clicked="handlePlayerClicked"
      />
    </ul>
  </div>
</template>

<script>
import ListPlayer from './ListPlayer.vue';

export default {
  props: {
    getPlayer: Function,
    players: Array,
  },
  components: {
    ListPlayer,
  },
  methods: {
    handlePlayerClicked(playerId) {
      // Call the getPlayer prop function with the id of the clicked player
      this.getPlayer(playerId);
    },
  },
};
</script>
