// vue/players_CRUD2/src/components/AuthUser.vue
<!-- 

  
  Student instructions to create this component:

  The functionality of this component is two fold: 
  1. Display a link that toggles between "Go to login", "Go to register", and "Logout" depending on the value of the isLoggedIn prop: By default, it is "Go to register", when the user is not logged in.  
  - User logged in: display "Logout". The link should emit a logout event when clicked.
  - User not logged in and in login: display "Go to register". 
  - User not logged in and in register: display "Go to login".
  
  2. When user is trying to log in or register, the component should display a form with two input fields and a submit button.  The form should have an id of "auth-form". The form should submit the username and password to the submit function when submitted. The input fields should be required.

  - One input field for username with an id of "username", name of "auth-username" and type of "text".
  - One input field for password with an id of "password", name of "auth-password" and type of "password".
  - A submit button with a class of "btn-auth" with the text "login" or "register" depending on the current state of the component. If the user is trying to login, the button should say "login" and emit a "login" event with the username and password. If the user is trying to register, the button should say "register" and emit a "register" event with the username and password.

  Once user is logged in or registered, the form should be hidden and the link should change to "Logout".

 -->

 <template>
  <div>
    <div v-if="isRegistering || isLoggingIn">
      <form v-if="!isLoggedIn" class="auth-form" id="auth-form" @submit.prevent="submitForm">
        <label for="username">Username:</label>
        <input
          id="username"
          name="auth-username"
          type="text"
          v-model="username"
          required
        />
        <label for="password">Password:</label>
        <input
          id="password"
          name="auth-password"
          type="password"
          v-model="password"
          required
        />
        <button type="submit" class="btn-auth">
          {{ isLoggingIn ? 'Login' : 'Register' }}
        </button>
      </form>
    </div>
    <div v-if="!isLoggedIn && !isRegistering">
      <a href="#" class="link" @click="toggleRegister">Go to register</a>
    </div>
    <div v-if="!isLoggedIn && isRegistering">
      <a href="#" class="link" @click="toggleLogin">Go to login</a>
    </div>
    <div v-if="isLoggedIn">
      <a href="#" class="link" @click="logoutUser">Logout</a>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      username: '',
      password: '',
      isLoggingIn: true,
      isRegistering: false,
    };
  },
  props: {
    isLoggedIn: Boolean,
  },
  methods: {
    toggleRegister() {
      this.isRegistering = true;
      this.isLoggingIn = false;
    },
    toggleLogin() {
      this.isRegistering = false;
      this.isLoggingIn = true;
    },
    submitForm() {
      if (this.isLoggingIn) {
        this.$emit('login', { username: this.username, password: this.password });
      } else {
        this.$emit('register', { username: this.username, password: this.password });
      }
    },
    logoutUser() {
      this.$emit('logout');
    },
  },
};
</script>

// react/players_CRUD2/src/components/AuthUser.jsx
/** @format
 * Student instructions:
 * Use the given template with props to create a AuthUser component similar to the AuthUser component in the Vue exercise. Instead of using a template, use JSX.
 *
 * isLoggedIn is a prop boolean that indicates if the user is logged in or not.
 * onLogin is a prop function that will be called when the form is submitted and user is in "login" view. It should be called with the username and password as arguments.
 * onRegister is a prop function that will be called when the form is submitted and user is in the "register" view. It should be called with the username and password as arguments.
 * onLogout is a prop function that will be called when the logout link is clicked. It should be called with no arguments.
 *
 * REMEMBER: use the same ids, classes and attributes as in the Vue exercise in the same places to pass the tests.
 */

import { useState } from "react";

export const AuthUser = ({ isLoggedIn, onLogin, onRegister, onLogout }) => {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [isLoggingIn, setIsLoggingIn] = useState(true);
  const [isRegistering, setIsRegistering] = useState(false);

  const toggleRegister = () => {
    setIsRegistering(true);
    setIsLoggingIn(false);
  };

  const toggleLogin = () => {
    setIsRegistering(false);
    setIsLoggingIn(true);
  };

  const submitForm = (event) => {
    event.preventDefault();
    if (isLoggingIn) {
      onLogin(username, password);
    } else {
      onRegister(username, password);
    }
    setUsername("");
    setPassword("");
  };

  const logoutUser = () => {
    onLogout();
  };

  return (
    <div>
      {/* Form for login/register */}
      {(!isLoggedIn && isLoggingIn) || (!isLoggedIn && isRegistering) ? (
        <form className="auth-form" id="auth-form" onSubmit={submitForm}>
          <label htmlFor="username">Username:</label>
          <input
            id="username"
            name="auth-username"
            type="text"
            value={username}
            onChange={(e) => setUsername(e.target.value)}
            required
          />
          <label htmlFor="password">Password:</label>
          <input
            id="password"
            name="auth-password"
            type="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            required
          />
          <button type="submit" className="btn-auth">
            {isLoggingIn ? "Login" : "Register"}
          </button>
        </form>
      ) : null}

      {/* Links to toggle between login/register and logout */}
      {!isLoggedIn && !isRegistering ? (
        <a href="#" className="link" onClick={toggleRegister}>
          Go to register
        </a>
      ) : null}
      {!isLoggedIn && isRegistering ? (
        <a href="#" className="link" onClick={toggleLogin}>
          Go to login
        </a>
      ) : null}
      {isLoggedIn ? (
        <a href="#" className="link" onClick={logoutUser}>
          Logout
        </a>
      ) : null}
    </div>
  );
};
