// react/players_CRUD2/src/components/ListPlayers.jsx
/** @format
 *
 * Student instructions:
 *
 * COPY YOUR CODE FROM THE PREVIOUS EXERCISE HERE.
 */

import { ListPlayer } from "./ListPlayer.jsx";

export const ListPlayers = ({ players, getPlayer }) => {
  const handlePlayerClicked = (playerId) => {
    getPlayer(playerId);
  };

  return (
    <div>
      <ul id="players-list">
        {players && players.length > 0 ? (
          players.map((player) => (
            <ListPlayer
              key={player.id}
              player={player}
              onClick={handlePlayerClicked}
            />
          ))
        ) : (
          <li>No players available</li>
        )}
      </ul>
    </div>
  );
};

// vue/players_CRUD/src/components/ListPlayers.vue
<!-- 
  Copy paste your code from the ListPlayer.vue file here from the previous exercise. No changes are needed if you managed to get the component to work properly in the previous exercise.
 -->

 <template>
  <div>
    <ul id="players-list">
      <ListPlayer
        v-for="player in players"
        :key="player.id"
        :player="player"
        @player-clicked="handlePlayerClicked"
      />
    </ul>
  </div>
</template>

<script>
import ListPlayer from './ListPlayer.vue';

export default {
  props: {
    getPlayer: Function,
    players: Array,
  },
  components: {
    ListPlayer,
  },
  methods: {
    handlePlayerClicked(playerId) {
      // Call the getPlayer prop function with the id of the clicked player
      this.getPlayer(playerId);
    },
  },
};
</script>
