// pinia/vue_pinia/src/components/ListPlayer.vue
<!-- 
  Copy paste your code from the ListPlayer.vue file here from the players_CRUD exercise of the Vue week.

  BEWARE: Only the player is passed to this component as a prop from now on. All the other data is fetched and updated in the redux store. Meaning you need to implement a method in the Pinia store that fetches the player when it is clicked and selects it as the selected player.
-->

<template>
  <li :id="'player-' + player.id" @click="handlePlayerClick" @keydown.enter="handlePlayerClick">
    <a href="#">
      {{ player.name }}
    </a>
  </li>
</template>

<script>
import { usePlayerStore } from '../pinia/playerStore';
export default {
  props: {
    player: {
      type: Object,
      required: true
    }
  },
  setup(props, { emit }) {
    const store = usePlayerStore();

    const handlePlayerClick = () => {
      store.setSelectedPlayer(props.player);
      emit('player-clicked', props.player);
    };

    return {
      handlePlayerClick
    };
  }
};
</script>

// redux/redux_thunk/src/components/ListPlayer.jsx
/** @format
 * Copy paste your code from the ListPlayer.jsx file here from the previous exercise
 * BEWARE: Only the player passed to this component as prop. All the other data is fetched and updated in the redux store.
 *
 * Here are the thunks that you can use to update the redux store:
 * - getSelectedPlayer, found in src\redux\actionCreators\thunks\ListPlayer.jsx
 */
import { useDispatch } from "react-redux";
import { getSelectedPlayer } from "../redux/actionCreators/thunks/ListPlayer";

export const ListPlayer = ({ name, id }) => {
  const dispatch = useDispatch();

  const handlePlayerClick = (e) => {
    e.preventDefault();
    dispatch(getSelectedPlayer(id));
  };

  return (
    <li id={`player-${id}`}>
      <a
        href="#"
        onClick={handlePlayerClick}
        onKeyDown={(e) => {
          if (e.key === "Enter") {
            handlePlayerClick();
          }
        }}
        tabIndex="0"
      >
        {name}
      </a>
    </li>
  );
};
